image: python:3.11


pipelines:
  default:
    - step: &lint
        name: Lint
        caches:
          - pip
        script:
          - pip install -r requirements_linting.txt
          - flake8

    - step: &type
        name: Type
        caches:
          - pip
        script:
          - pip install -r requirements_typing.txt
          - mypy

    - step: &test
        name: Test
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - pip install -r requirements_testing.txt
          - pytest
  
  branches:
    deploy:
      - step: *lint
      - step: *type
      - step: *test
      - step:
          name: Build
          services:
            - docker
          script:
            - docker build -t joehitchen/sipp-tracker .
            - docker save --output sipp-tracker.docker joehitchen/sipp-tracker
          artifacts:
            - sipp-tracker.docker
  
      - step:
          name: Verify
          services:
            - docker
          script:
            - docker load --input sipp-tracker.docker
            - docker run --rm joehitchen/sipp-tracker  sh -c "export PATH=\"\$HOME/.local/bin:\$PATH\" && pip install -r requirements_testing.txt && pytest"
  
      - step:
          name: Publish
          deployment: Docker
          services:
            - docker
          script:
            - docker load --input sipp-tracker.docker
            - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - docker push joehitchen/sipp-tracker

