# Generated by Django 5.2 on 2025-04-11 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_price_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricepoint',
            old_name='price_pence',
            new_name='hundredths',
        ),
    ]
