# Generated by Django 5.2 on 2025-04-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0005_holding_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='monitor_price',
            field=models.BooleanField(default=True),
        ),
    ]
