# Generated by Django 5.2 on 2025-06-07 21:14

from django.db import migrations, models
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor as SchemaEditor


SIPP = 'SIPP'
ISA = 'ISA'


def migrate_portfolios(apps: Apps, schema_editor: SchemaEditor) -> None:
    Portfolio = apps.get_model('invest', 'Portfolio')
    Holding = apps.get_model('invest', 'Holding')

    sipp = Portfolio.objects.create(type = SIPP)
    isa = Portfolio.objects.create(type = ISA)

    Holding.objects.filter(portfolio_old=SIPP).update(portfolio=sipp)
    Holding.objects.filter(portfolio_old=ISA).update(portfolio=isa)


def reverse_portfolios(apps: Apps, schema_editor: SchemaEditor) -> None:
    Holding = apps.get_model('invest', 'Holding')

    Holding.objects.filter(portfolio__type=SIPP).update(portfolio_old=SIPP)
    Holding.objects.filter(portfolio__type=ISA).update(portfolio_old=ISA)


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0007_holding_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='portfolio',
            new_name='portfolio_old',
        ),
        migrations.AlterField(
            model_name='holding',
            name='portfolio_old',
            field=models.CharField(choices=[(SIPP, SIPP), (ISA, ISA)], max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(SIPP, SIPP), (ISA, ISA)], max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=models.deletion.CASCADE, related_name='holdings', to='invest.portfolio'),
        ),
        migrations.RunPython(
            code=migrate_portfolios,
            reverse_code=reverse_portfolios,
        ),
        migrations.RemoveField(
            model_name='holding',
            name='portfolio_old',
        ),
        migrations.AlterField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='holdings', to='invest.portfolio'),
        ),
    ]
