# Generated by Django 5.2.8 on 2025-12-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0008_portfolio_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='type',
            field=models.CharField(choices=[('ACC', 'Accumulation'), ('INC', 'Income')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='region',
            field=models.CharField(choices=[('UK', 'United Kingdom'), ('EU', 'Europe'), ('NA', 'North America'), ('APAC', 'Asia Pacific'), ('LAM', 'Latin America'), ('EMG', 'Emerging Markets'), ('GLB', 'Global')], default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='green',
            field=models.BooleanField(default=False),
        ),
    ]
