# Generated by Django 5.2.8 on 2026-01-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0009_fund_green_fund_region_fund_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='reinvested',
            field=models.BooleanField(default=False),
        ),
    ]
