# Generated by Django 5.2 on 2025-04-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255)),
                ('full_name', models.TextField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('bought_on', models.DateField()),
                ('bought_price', models.IntegerField()),
                ('bought_quantity', models.FloatField()),
                ('url', models.URLField(max_length=255)),
            ],
        ),
    ]
