# Generated by Django 5.2 on 2025-04-07 12:33

import django.db.models.deletion
from django.db import migrations, models
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor as SchemaEditor


def migrate_price_points(apps: Apps, schema_editor: SchemaEditor) -> None:
    PricePoint = apps.get_model('sipp', 'PricePoint')
    Fund = apps.get_model('sipp', 'Fund')

    for fund in Fund.objects.all():
        PricePoint.objects.create(
            fund=fund,
            date=fund.bought_on,
            price_pence=fund.bought_price,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sipp', '0001_funds'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price_pence', models.IntegerField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='sipp.fund')),
            ],
            options={
                'db_table': 'sipp_price_point',
                'ordering': ['fund', 'date'],
                'unique_together': {('fund', 'date')},
            },
        ),
        migrations.RunPython(
            code=migrate_price_points,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
