# Generated by Django 5.2 on 2025-04-12 11:33

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor as SchemaEditor


def migrate_holdings(apps: Apps, schema_editor: SchemaEditor) -> None:
    Fund = apps.get_model('sipp', 'Fund')

    for fund in Fund.objects.all():
        fund.holdings.create(
            quantity=fund.bought_quantity,
            bought_on=fund.bought_on,
            bought_at=fund.bought_price,
        )


def reset_fund_holdings(apps: Apps, schema_editor: SchemaEditor) -> None:
    Fund = apps.get_model('sipp', 'Fund')

    for fund in Fund.objects.all():
        holding = fund.holdings.first()

        if holding:
            fund.bought_on = holding.bought_on
            fund.bought_price = holding.bought_at
            fund.bought_quantity = holding.quantity
        else:
            fund.bought_on = timezone.now().date()
            fund.bought_price = 0
            fund.bought_quantity = 0
        
        fund.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sipp', '0003_rename_price_to_hundredths'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('bought_on', models.DateField()),
                ('bought_at', models.IntegerField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='sipp.fund')),
            ],
            options={
                'ordering': ['fund', 'bought_on', '-quantity'],
            },
        ),
        migrations.AlterField(
            model_name='fund',
            name='bought_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='bought_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='bought_quantity',
            field=models.FloatField(null=True),
        ),
        migrations.RunPython(
            code=migrate_holdings,
            reverse_code=reset_fund_holdings,
        ),
        migrations.RemoveField(
            model_name='fund',
            name='bought_on',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='bought_price',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='bought_quantity',
        ),
    ]
