# Generated by Django 5.2 on 2025-04-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipp', '0004_holdings'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='sold_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='sold_on',
            field=models.DateField(null=True),
        ),
    ]
