# Generated by Django 5.2 on 2025-05-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipp', '0006_fund_monitor_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='portfolio',
            field=models.CharField(choices=[('SIPP', 'SIPP'), ('ISA', 'ISA')], default='SIPP', max_length=4),
            preserve_default=False,
        ),
    ]
