name: Quality Control

on:
  push:
  schedule:
    - cron: '37 3 * * 5'
      timezone: 'Europe/London'


jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements_linting.txt

      - name: Install dependencies
        run: pip install -r requirements_linting.txt

      - name: Run checks
        run: flake8

  typing:
    name: Typing
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements_typing.txt

      - name: Install dependencies
        run: pip install -r requirements_typing.txt

      - name: Run checks
        run: mypy

  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: |
            requirements_testing.txt
            requirements.txt

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements_testing.txt

      - name: Run checks
        run: pytest
